services:
  autophone:
    container_name: autophone
    image: autophone:latest
    build: .
    ports:
      - "${SERVICE_PORT}:8080"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./user_data:/app/user_data
    restart: unless-stopped
